groups:
- name: example
  rules:
  - alert: HighRequestRate
    expr: http_requests_total > 100
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High request rate detected"
