// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.6.1
// source: proto/shop_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShopByID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId int32 `protobuf:"varint,1,opt,name=ShopId,proto3" json:"ShopId,omitempty"`
}

func (x *ShopByID) Reset() {
	*x = ShopByID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shop_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopByID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopByID) ProtoMessage() {}

func (x *ShopByID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopByID.ProtoReflect.Descriptor instead.
func (*ShopByID) Descriptor() ([]byte, []int) {
	return file_proto_shop_service_proto_rawDescGZIP(), []int{0}
}

func (x *ShopByID) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type ReqAllShop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqAllShop) Reset() {
	*x = ReqAllShop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shop_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAllShop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAllShop) ProtoMessage() {}

func (x *ReqAllShop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAllShop.ProtoReflect.Descriptor instead.
func (*ReqAllShop) Descriptor() ([]byte, []int) {
	return file_proto_shop_service_proto_rawDescGZIP(), []int{1}
}

type Shop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	OwnerId int32  `protobuf:"varint,3,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
}

func (x *Shop) Reset() {
	*x = Shop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shop_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shop) ProtoMessage() {}

func (x *Shop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shop.ProtoReflect.Descriptor instead.
func (*Shop) Descriptor() ([]byte, []int) {
	return file_proto_shop_service_proto_rawDescGZIP(), []int{2}
}

func (x *Shop) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Shop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shop) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type AllShop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shop []*Shop `protobuf:"bytes,1,rep,name=Shop,proto3" json:"Shop,omitempty"`
}

func (x *AllShop) Reset() {
	*x = AllShop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shop_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllShop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllShop) ProtoMessage() {}

func (x *AllShop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllShop.ProtoReflect.Descriptor instead.
func (*AllShop) Descriptor() ([]byte, []int) {
	return file_proto_shop_service_proto_rawDescGZIP(), []int{3}
}

func (x *AllShop) GetShop() []*Shop {
	if x != nil {
		return x.Shop
	}
	return nil
}

type ShopByOwnerId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId int32 `protobuf:"varint,1,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
}

func (x *ShopByOwnerId) Reset() {
	*x = ShopByOwnerId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shop_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopByOwnerId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopByOwnerId) ProtoMessage() {}

func (x *ShopByOwnerId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopByOwnerId.ProtoReflect.Descriptor instead.
func (*ShopByOwnerId) Descriptor() ([]byte, []int) {
	return file_proto_shop_service_proto_rawDescGZIP(), []int{4}
}

func (x *ShopByOwnerId) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

var File_proto_shop_service_proto protoreflect.FileDescriptor

var file_proto_shop_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x22, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x79, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53,
	0x68, 0x6f, 0x70, 0x49, 0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x41, 0x6c, 0x6c, 0x53,
	0x68, 0x6f, 0x70, 0x22, 0x44, 0x0a, 0x04, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x07, 0x41, 0x6c, 0x6c,
	0x53, 0x68, 0x6f, 0x70, 0x12, 0x1f, 0x0a, 0x04, 0x53, 0x68, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x52,
	0x04, 0x53, 0x68, 0x6f, 0x70, 0x22, 0x29, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x79, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x32, 0x47, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x38, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70,
	0x42, 0x79, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x6c, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_shop_service_proto_rawDescOnce sync.Once
	file_proto_shop_service_proto_rawDescData = file_proto_shop_service_proto_rawDesc
)

func file_proto_shop_service_proto_rawDescGZIP() []byte {
	file_proto_shop_service_proto_rawDescOnce.Do(func() {
		file_proto_shop_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_shop_service_proto_rawDescData)
	})
	return file_proto_shop_service_proto_rawDescData
}

var file_proto_shop_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_shop_service_proto_goTypes = []interface{}{
	(*ShopByID)(nil),      // 0: proto.ShopByID
	(*ReqAllShop)(nil),    // 1: proto.ReqAllShop
	(*Shop)(nil),          // 2: proto.Shop
	(*AllShop)(nil),       // 3: proto.AllShop
	(*ShopByOwnerId)(nil), // 4: proto.ShopByOwnerId
}
var file_proto_shop_service_proto_depIdxs = []int32{
	2, // 0: proto.AllShop.Shop:type_name -> proto.Shop
	4, // 1: proto.ShopService.GetShopByOwnerId:input_type -> proto.ShopByOwnerId
	3, // 2: proto.ShopService.GetShopByOwnerId:output_type -> proto.AllShop
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_shop_service_proto_init() }
func file_proto_shop_service_proto_init() {
	if File_proto_shop_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_shop_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopByID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shop_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAllShop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shop_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shop_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllShop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shop_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopByOwnerId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_shop_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shop_service_proto_goTypes,
		DependencyIndexes: file_proto_shop_service_proto_depIdxs,
		MessageInfos:      file_proto_shop_service_proto_msgTypes,
	}.Build()
	File_proto_shop_service_proto = out.File
	file_proto_shop_service_proto_rawDesc = nil
	file_proto_shop_service_proto_goTypes = nil
	file_proto_shop_service_proto_depIdxs = nil
}
