// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: shop_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShopByID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId int32 `protobuf:"varint,1,opt,name=ShopId,proto3" json:"ShopId,omitempty"`
}

func (x *ShopByID) Reset() {
	*x = ShopByID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopByID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopByID) ProtoMessage() {}

func (x *ShopByID) ProtoReflect() protoreflect.Message {
	mi := &file_shop_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopByID.ProtoReflect.Descriptor instead.
func (*ShopByID) Descriptor() ([]byte, []int) {
	return file_shop_service_proto_rawDescGZIP(), []int{0}
}

func (x *ShopByID) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type ReqAllShop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqAllShop) Reset() {
	*x = ReqAllShop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAllShop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAllShop) ProtoMessage() {}

func (x *ReqAllShop) ProtoReflect() protoreflect.Message {
	mi := &file_shop_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAllShop.ProtoReflect.Descriptor instead.
func (*ReqAllShop) Descriptor() ([]byte, []int) {
	return file_shop_service_proto_rawDescGZIP(), []int{1}
}

type Shop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *Shop) Reset() {
	*x = Shop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shop) ProtoMessage() {}

func (x *Shop) ProtoReflect() protoreflect.Message {
	mi := &file_shop_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shop.ProtoReflect.Descriptor instead.
func (*Shop) Descriptor() ([]byte, []int) {
	return file_shop_service_proto_rawDescGZIP(), []int{2}
}

func (x *Shop) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Shop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AllShop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shop []*Shop `protobuf:"bytes,1,rep,name=Shop,proto3" json:"Shop,omitempty"`
}

func (x *AllShop) Reset() {
	*x = AllShop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllShop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllShop) ProtoMessage() {}

func (x *AllShop) ProtoReflect() protoreflect.Message {
	mi := &file_shop_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllShop.ProtoReflect.Descriptor instead.
func (*AllShop) Descriptor() ([]byte, []int) {
	return file_shop_service_proto_rawDescGZIP(), []int{3}
}

func (x *AllShop) GetShop() []*Shop {
	if x != nil {
		return x.Shop
	}
	return nil
}

var File_shop_service_proto protoreflect.FileDescriptor

var file_shop_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x08, 0x53,
	0x68, 0x6f, 0x70, 0x42, 0x79, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x68, 0x6f, 0x70, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x22,
	0x0c, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x41, 0x6c, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x22, 0x2a, 0x0a,
	0x04, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x07, 0x41, 0x6c, 0x6c,
	0x53, 0x68, 0x6f, 0x70, 0x12, 0x1f, 0x0a, 0x04, 0x53, 0x68, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x52,
	0x04, 0x53, 0x68, 0x6f, 0x70, 0x32, 0x6b, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x68,
	0x6f, 0x70, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x41, 0x6c,
	0x6c, 0x53, 0x68, 0x6f, 0x70, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c,
	0x6c, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x2b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70,
	0x42, 0x79, 0x49, 0x44, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f,
	0x70, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68,
	0x6f, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shop_service_proto_rawDescOnce sync.Once
	file_shop_service_proto_rawDescData = file_shop_service_proto_rawDesc
)

func file_shop_service_proto_rawDescGZIP() []byte {
	file_shop_service_proto_rawDescOnce.Do(func() {
		file_shop_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_shop_service_proto_rawDescData)
	})
	return file_shop_service_proto_rawDescData
}

var file_shop_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shop_service_proto_goTypes = []interface{}{
	(*ShopByID)(nil),   // 0: proto.ShopByID
	(*ReqAllShop)(nil), // 1: proto.ReqAllShop
	(*Shop)(nil),       // 2: proto.Shop
	(*AllShop)(nil),    // 3: proto.AllShop
}
var file_shop_service_proto_depIdxs = []int32{
	2, // 0: proto.AllShop.Shop:type_name -> proto.Shop
	1, // 1: proto.ShopService.GetAllShop:input_type -> proto.ReqAllShop
	0, // 2: proto.ShopService.GetShopByID:input_type -> proto.ShopByID
	3, // 3: proto.ShopService.GetAllShop:output_type -> proto.AllShop
	2, // 4: proto.ShopService.GetShopByID:output_type -> proto.Shop
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shop_service_proto_init() }
func file_shop_service_proto_init() {
	if File_shop_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shop_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopByID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAllShop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllShop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shop_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_service_proto_goTypes,
		DependencyIndexes: file_shop_service_proto_depIdxs,
		MessageInfos:      file_shop_service_proto_msgTypes,
	}.Build()
	File_shop_service_proto = out.File
	file_shop_service_proto_rawDesc = nil
	file_shop_service_proto_goTypes = nil
	file_shop_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShopServiceClient is the client API for ShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShopServiceClient interface {
	GetAllShop(ctx context.Context, in *ReqAllShop, opts ...grpc.CallOption) (*AllShop, error)
	GetShopByID(ctx context.Context, in *ShopByID, opts ...grpc.CallOption) (*Shop, error)
}

type shopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopServiceClient(cc grpc.ClientConnInterface) ShopServiceClient {
	return &shopServiceClient{cc}
}

func (c *shopServiceClient) GetAllShop(ctx context.Context, in *ReqAllShop, opts ...grpc.CallOption) (*AllShop, error) {
	out := new(AllShop)
	err := c.cc.Invoke(ctx, "/proto.ShopService/GetAllShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetShopByID(ctx context.Context, in *ShopByID, opts ...grpc.CallOption) (*Shop, error) {
	out := new(Shop)
	err := c.cc.Invoke(ctx, "/proto.ShopService/GetShopByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServiceServer is the server API for ShopService service.
type ShopServiceServer interface {
	GetAllShop(context.Context, *ReqAllShop) (*AllShop, error)
	GetShopByID(context.Context, *ShopByID) (*Shop, error)
}

// UnimplementedShopServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShopServiceServer struct {
}

func (*UnimplementedShopServiceServer) GetAllShop(context.Context, *ReqAllShop) (*AllShop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllShop not implemented")
}
func (*UnimplementedShopServiceServer) GetShopByID(context.Context, *ShopByID) (*Shop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopByID not implemented")
}

func RegisterShopServiceServer(s *grpc.Server, srv ShopServiceServer) {
	s.RegisterService(&_ShopService_serviceDesc, srv)
}

func _ShopService_GetAllShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqAllShop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetAllShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShopService/GetAllShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetAllShop(ctx, req.(*ReqAllShop))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetShopByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetShopByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShopService/GetShopByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetShopByID(ctx, req.(*ShopByID))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ShopService",
	HandlerType: (*ShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllShop",
			Handler:    _ShopService_GetAllShop_Handler,
		},
		{
			MethodName: "GetShopByID",
			Handler:    _ShopService_GetShopByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop_service.proto",
}
